export { default as Auth } from "./auth/Auth"
export { default as Navbar } from "./navbar/Navbar"
export { default as CreatePost } from "./navbar/CreatePost"
export { default as Suggested } from './Suggested'
export { default as EditProfile } from './profile/EditProfile'
export { default as ProfilePosts } from './profile/ProfilePosts'
export { default as ProfileInfo } from './profile/ProfileInfo'
export { default as Search } from './Search'
export { default as Modal } from './modals/Modal'
export { default as Card } from './grams/Card'
export { default as Cards } from './grams/Cards'
export { default as ViewMore } from './grams/ViewMore'
